In [ ]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np

iris = load_iris()
X, y = iris.data, iris.target
feature_names = iris.feature_names
target_names = iris.target_names

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=111)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression(max_iter=200, multi_class="multinomial")
model.fit(X_train_scaled, y_train)
print("Trained")

coef = model.coef_

importance = np.sum(np.abs(coef), axis=0)
print("Overall feature importance:\n")
for feature_name, score in sorted(zip(feature_names, importance), key=lambda x: -x[1]):
    print(f"  {feature_name}: {score:.3f}")

y_pred = model.predict(X_test_scaled)
print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average="macro"))
print("Recall:", recall_score(y_test, y_pred, average="macro"))
print("F1 Score:", f1_score(y_test, y_pred, average="macro"))


Overall feature importance:

  petal width (cm): 4.917
  petal length (cm): 4.331
  sepal length (cm): 2.103
  sepal width (cm): 1.959

Accuracy: 0.9
Precision: 0.8968253968253969
Recall: 0.8791208791208792
F1 Score: 0.886039886039886


C:\Users\aibel\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


In [1]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


iris = load_iris()
X, y = iris.data, iris.target


X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)


model = LogisticRegression(max_iter=200, multi_class='multinomial')
model.fit(X_train, y_train)

print("Predictions:", model.predict(X_test[:5]))
print("Probabilities:", model.predict_proba(X_test[:5]))


Predictions: [1 0 2 1 1]
Probabilities: [[3.80003288e-03 8.27709981e-01 1.68489986e-01]
 [9.46943486e-01 5.30563152e-02 1.99071285e-07]
 [8.84349819e-09 1.54870684e-03 9.98451284e-01]
 [6.47949015e-03 7.92188507e-01 2.01332003e-01]
 [1.45577986e-03 7.74084104e-01 2.24460116e-01]]


C:\Users\aibel\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
